version: "3.8"
services:
    host-app:
      container_name: host-app
      build: .
      restart: always
      ports:
        - "8080:8080"
      depends_on:
        - mongo-db
      environment:
        - SPRING_DATA_MONGODB_HOST=mongo-db
        - SPRING_DATA_MONGODB_PORT=27017
        - SPRING_DATA_MONGODB_DATABASE=test-db
      networks:
        database: { }

networks:
  database:
    external: true
